version: '3.8'

services:
  mysql:
    image: mysql:8.4
    container_name: tc-db
    network_mode: host
    restart: always
    environment:
      - MYSQL_DATABASE=lanchonete
      - MYSQL_ROOT_PASSWORD=senhasegura
      - MYSQL_USER=tc_user
      - MYSQL_PASSWORD=senhasegura
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql

  tech-challenge:
    build:
      context: .
      dockerfile: Dockerfile
    image: tech-challenge-1:latest
    container_name: tc-app
    network_mode: host
    depends_on:
      - mysql